<b>Hello Phantom</b> files to be run on a PC connected through a network to the Pi
<ul>
  <li><b>!Sandbox:</b> Used to test out unfamiliar packages, can be used as a "copy/paste" template for some packages. Exclamation mark is to ensure it's the top folder when sorted alphabetically</li>
  <li><b>__pycache__:</b> Generated by Python, when calling functions from another directory</li>
  <li><b>gpts:</b> Contains classes of GPT4ALL, intended to word the response sent back to the Pi; Called by gpt.py once user intent has been determined</li>
  <li><b>socketing:</b> Contains client and server classes to send strings to and from (respectively) between the Pi and the PC; Currently blocked by school firewall</li>
  <li><b>webscrape:</b> Contains scrapers for weather (sourced from a local weather site), events (sourced from an unofficial .csv because the Main Office still hasn't given us an actual comprehensive spreadsheet), and facts (just asks the offline Llama3 model).</li>
  <li><b>HelloPhantom:</b> <b>To be run by the PC, organizes websocketing and GPT calling into one loop</b></li>
  <li><b>gpt.py:</b> GPT designed to classify intent, calls additional GPTs and webscrapers based on said intent (currently <b>very unoptimized</b>)</li>
  <li><b>PiPhantom:</b> To be run by either the Pi (adjusting file paths, loop condition, GPIO, tts, and stt as needed) or another terminal of the PC alongside HelloPhantom.py</li>
</ul>
